function Write-JsDeps {
	param($root, $prefix, $exclusion)
	
	"// This file was autogenerated"
	"// Please do not edit."
	
	Get-ChildItem $root -Recurse -Include *.js -Exclude $exclusion | sort FullName |
		%{ Create-DepsLine $root $prefix $_.FullName }
}

function Create-DepsLine {
	param($root, $prefix, $path)
	
	$prefixedPath = Get-PrefixedPath $root $prefix $path
	$source = Get-Content $path -ReadCount 0
	$provides = Parse 'provide' $source
	$requires = Parse 'require' $source
	"goog.addDependency('$prefixedPath', [$provides], [$requires]);"
}

$parsers = @{ provide = [regex] "goog\.provide\(([^\)]+)\)"; require = [regex] "goog\.require\(([^\)]+)\)" }

function Parse {
	param($what, $from)
	
	($parsers[$what].Matches($from ) | %{ $_.Groups[1].Value }) -join ', '
}

function Get-PrefixedPath {
	$path.Replace($root, $prefix).Replace('\', '/').Replace('//', '/')
}